# Purpose this file performs exploratory data analysis (EDA) on the cleaned dataset using the final chosen project variables
import os
import pandas as pd
import matplotlib.pyplot as plt
# made the following few lines to make sure the right file is selected if the TA obtains a different name for the files by using file path and also 
# double checks the name
DATA_FILE_PATH=os.path.join("data","processed","powerlifting_working.csv")
FIGURES_FOLDER="figures"
NOTES_FOLDER="notes"
EDA_SUMMARY_PATH=os.path.join(NOTES_FOLDER,"eda_summary.txt")
os.makedirs(FIGURES_FOLDER,exist_ok=True)
os.makedirs(NOTES_FOLDER,exist_ok=True)
if not os.path.exists(DATA_FILE_PATH):
    print("ERROR: Could not find cleaned dataset.")
    print("Expected location:",DATA_FILE_PATH)
    raise FileNotFoundError(DATA_FILE_PATH)
#loading the data
print("Loading cleaned dataset...")
df = pd.read_csv(DATA_FILE_PATH, low_memory=False)
print("Dataset loaded.")
print()
#keep only columns needed for eda
needed_columns=["TotalKg","BodyweightKg","Age","Sex", "Equipment", "Dots"]
for col in needed_columns:
    if col not in df.columns:
        print("ERROR: Missing required EDA column:",col)
        raise ValueError(f"Missing column: {col}")
eda_df = df[needed_columns].copy()
#summary of the eda
print("EDA dataset shape:")
print(eda_df.shape)
print()
print("EDA columns:")
print(eda_df.columns.tolist())
print("Missing values in EDA dataset:")
print(eda_df.isna().sum())

# create version with age kept and version without age missing
eda_age_df=eda_df.dropna(subset=["Age"]).copy()
print("Rows in EDA dataset before dropping missing Age:")
print(len(eda_df))
print("Rows in EDA dataset after dropping missing Age:")
print(len(eda_age_df))

# descriptive statistics
numeric_cols=["TotalKg","BodyweightKg","Age","Dots"]
desc_stats=eda_age_df[numeric_cols].describe()
mean_total_by_sex=eda_age_df.groupby("Sex")["TotalKg"].mean().sort_values(ascending=False)
mean_total_by_equipment=eda_age_df.groupby("Equipment")["TotalKg"].mean().sort_values(ascending=False)
mean_dots_by_sex=eda_age_df.groupby("Sex")["Dots"].mean().sort_values(ascending=False)
mean_dots_by_equipment=eda_age_df.groupby("Equipment")["Dots"].mean().sort_values(ascending=False)
corr_matrix=eda_age_df[numeric_cols].corr()

with open(EDA_SUMMARY_PATH, "w", encoding="utf-8") as f:
    f.write("EDA SUMMARY\n\n")
    f.write("Dataset used for EDA:\n")
    f.write(DATA_FILE_PATH + "\n\n")
    f.write("Columns used for EDA:\n")
    for col in needed_columns:f.write(f"- {col}\n")
    f.write("\n")
    f.write("Rows before dropping missing Age:\n")
    f.write(str(len(eda_df)) + "\n\n")
    f.write("Rows after dropping missing Age:\n")
    f.write(str(len(eda_age_df)) + "\n\n")
    f.write("Missing values in EDA dataset:\n")
    f.write(eda_df.isna().sum().to_string())
    f.write("\n\n")
    f.write("Descriptive statistics:\n")
    f.write(desc_stats.to_string())
    f.write("\n\n")
    f.write("Mean TotalKg by Sex:\n")
    f.write(mean_total_by_sex.to_string())
    f.write("\n\n")
    f.write("Mean TotalKg by Equipment:\n")
    f.write(mean_total_by_equipment.to_string())
    f.write("\n\n")
    f.write("Mean Dots by Sex:\n")
    f.write(mean_dots_by_sex.to_string())
    f.write("\n\n")
    f.write("Mean Dots by Equipment:\n")
    f.write(mean_dots_by_equipment.to_string())
    f.write("\n\n")
    f.write("Correlation matrix:\n")
    f.write(corr_matrix.to_string())
    f.write("\n")
print("EDA summary text file created:")
print(EDA_SUMMARY_PATH)
print()

#figure 1: histogram of TotalKg
plt.figure(figsize=(8, 5))
plt.hist(eda_age_df["TotalKg"], bins=50)
plt.title("Distribution of TotalKg")
plt.xlabel("TotalKg")
plt.ylabel("Frequency")
plt.tight_layout()
plt.savefig(os.path.join(FIGURES_FOLDER,"hist_totalkg.png"))
plt.close()
# figure 2 histogram of BodyweightKg
plt.figure(figsize=(8,5))
plt.hist( eda_age_df["BodyweightKg"],bins=50)
plt.title("Distribution of BodyweightKg")
plt.xlabel("BodyweightKg")
plt.ylabel("Frequency")
plt.tight_layout()
plt.savefig( os.path.join(FIGURES_FOLDER, "hist_bodyweightkg.png"))
plt.close()
# figure 3: histogram of Dots
plt.figure( figsize=(8,5))
plt.hist(eda_age_df["Dots"], bins=50)
plt.title("Distribution of Dots")
plt.xlabel( "Dots")
plt.ylabel("Frequency")
plt.tight_layout()
plt.savefig( os.path.join(FIGURES_FOLDER, "hist_dots.png"))
plt.close()
# fig 4: scatterplot BodyweightKg vs TotalKg
sample_scatter=eda_age_df.sample(n=min(10000, len(eda_age_df)), random_state=42)
plt.figure(figsize=(8,5))
plt.scatter(sample_scatter["BodyweightKg"],sample_scatter["TotalKg"],alpha=0.3)
plt.title("BodyweightKg vs TotalKg")
plt.xlabel("BodyweightKg")
plt.ylabel("TotalKg")
plt.tight_layout()
plt.savefig(os.path.join(FIGURES_FOLDER,"scatter_bodyweight_total.png"))
plt.close()
# fig 5: scatterplot BodyweightKg vs Dots
plt.figure(figsize=(8,5))
plt.scatter(sample_scatter["BodyweightKg"], sample_scatter["Dots"], alpha=0.3)
plt.title("BodyweightKg vs Dots")
plt.xlabel("BodyweightKg")
plt.ylabel("Dots")
plt.tight_layout()
plt.savefig(os.path.join(FIGURES_FOLDER, "scatter_bodyweight_dots.png"))
plt.close()
# fig 6: boxplot TotalKg by Sex
sex_order = sorted(eda_age_df["Sex"].dropna().unique().tolist())
sex_data = [eda_age_df.loc[eda_age_df["Sex"] == sex, "TotalKg"] for sex in sex_order]
plt.figure(figsize=(8, 5))
plt.boxplot(sex_data, labels=sex_order)
plt.title("TotalKg by Sex")
plt.xlabel("Sex")
plt.ylabel("TotalKg")
plt.tight_layout()
plt.savefig(os.path.join(FIGURES_FOLDER, "boxplot_total_by_sex.png"))
plt.close()
# fig7: boxplot TotalKg by equipment
equip_order = sorted(eda_age_df["Equipment"].dropna().unique().tolist())
equip_data = [eda_age_df.loc[eda_age_df["Equipment"] == eq, "TotalKg"] for eq in equip_order]
plt.figure(figsize=(10, 6))
plt.boxplot(equip_data, labels=equip_order)
plt.title("TotalKg by Equipment")
plt.xlabel("Equipment")
plt.ylabel("TotalKg")
plt.xticks(rotation=30)
plt.tight_layout()
plt.savefig(os.path.join(FIGURES_FOLDER, "boxplot_total_by_equipment.png"))
plt.close()
#fig 8: boxplot DOTS by equipment
equip_dots_data = [eda_age_df.loc[eda_age_df["Equipment"] == eq, "Dots"] for eq in equip_order]
plt.figure(figsize=(10, 6))
plt.boxplot(equip_dots_data, labels=equip_order)
plt.title("Dots by Equipment")
plt.xlabel("Equipment")
plt.ylabel("Dots")
plt.xticks(rotation=30)
plt.tight_layout()
plt.savefig(os.path.join(FIGURES_FOLDER, "boxplot_dots_by_equipment.png"))
plt.close()
print("EDA figures saved in figures/")
print("Created files:")
print("- hist_totalkg.png")
print("- hist_bodyweightkg.png")
print("- hist_dots.png")
print("- scatter_bodyweight_total.png")
print("- scatter_bodyweight_dots.png")
print("- boxplot_total_by_sex.png")
print("- boxplot_total_by_equipment.png")
print("- boxplot_dots_by_equipment.png")
print()
print("EDA step finished.")